server:
  port: 8082

spring:
  application:
    name: prize-wheel-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://amway-service-registry:8761/eureka/
  instance:
    hostname: amway-prize-wheel-service