server:
  port: 8081

spring:
  application:
    name: calculator-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://amway-service-registry:8761/eureka/
  instance:
    hostname: amway-calculator-service